on:
  workflow_call:
    inputs:
      csharpier-version:
        required: true
        type: string

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
      - run: dotnet tool install csharpier --version ${{ inputs.csharpier-version }}
      - run: dotnet csharpier check .